<?php

use Illuminate\Database\Seeder;

class CountriesSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = [["id"=>1,"name"=>"Afghanistan","code"=>"AF"],
        ["id"=>2,"name"=>"African Rep.","code"=>'CF'],
        ["id"=>3,"name"=>"Albania","code"=>"AL"],
        ["id"=>4,"name"=>"Algeria","code"=>"DZ"],
        ["id"=>5,"name"=>"Andorra","code"=>"AD"],
        ["id"=>6,"name"=>"Angola","code"=>"AO"],
        ["id"=>7,"name"=>"Argentina","code"=>"AR"],
        ["id"=>8,"name"=>"Armenia","code"=>"AM"],
        ["id"=>9,"name"=>"Australia","code"=>"AU"],
        ["id"=>10,"name"=>"Austria","code"=>"AT"],
        ["id"=>11,"name"=>"Azerbaijan","code"=>"AZ"],
        ["id"=>12,"name"=>"Bahamas","code"=>"BS"],
        ["id"=>13,"name"=>"Bahrain","code"=>"BH"],
        ["id"=>14,"name"=>"Bangladesh","code"=>"BD"],
        ["id"=>15,"name"=>"Barbados","code"=>"BB"],
        ["id"=>16,"name"=>"Belarus","code"=>"BY"],
        ["id"=>17,"name"=>"Belgium","code"=>"BE"],
        ["id"=>18,"name"=>"Belize","code"=>"BZ"],
        ["id"=>19,"name"=>"Benin","code"=>"BJ"],
        ["id"=>20,"name"=>"Bhutan","code"=>"BT"],
        ["id"=>21,"name"=>"Bolivia","code"=>"BO"],
        ["id"=>22,"name"=>"Bosnia","code"=>"BA"],
        ["id"=>23,"name"=>"Botswana","code"=>"BW"],
        ["id"=>24,"name"=>"Brasil","code"=>'BR'],
        ["id"=>25,"name"=>"Brunei","code"=>"BN"],
        ["id"=>26,"name"=>"Bulgaria","code"=>"BG"],
        ["id"=>27,"name"=>"Burkina Faso","code"=>"BF"],
        ["id"=>28,"name"=>"Burundi","code"=>"BI"],
        ["id"=>29,"name"=>"Cambodia","code"=>"KH"],
        ["id"=>30,"name"=>"Cameroon","code"=>"CM"],
        ["id"=>31,"name"=>"Canada","code"=>"CA"],
        ["id"=>32,"name"=>"Cape_Verde","code"=>'CV'],
        ["id"=>33,"name"=>"Chile","code"=>"CL"],
        ["id"=>34,"name"=>"China","code"=>"CN"],
        ["id"=>35,"name"=>"Chinese Taipei","code"=>"TW"],
        ["id"=>36,"name"=>"Colombia","code"=>"CO"],
        ["id"=>37,"name"=>"Congo","code"=>"CG"],
        ["id"=>38,"name"=>"Croatia","code"=>"HR"],
        ["id"=>39,"name"=>"Cuba","code"=>"CU"],
        ["id"=>40,"name"=>"Cyprus","code"=>"CY"],
        ["id"=>41,"name"=>"Czech Rep. ","code"=>"CZ"],
        ["id"=>42,"name"=>"Denmark","code"=>"DK"],
        ["id"=>43,"name"=>"Ecuador","code"=>"EC"],
        ["id"=>44,"name"=>"Egypt","code"=>"EG"],
        ["id"=>45,"name"=>"Eritrea","code"=>"ER"],
        ["id"=>46,"name"=>"Estonia","code"=>"EE"],
        ["id"=>47,"name"=>"Ethiopia","code"=>"ET"],
        ["id"=>48,"name"=>"Europe","code"=>null],
        ["id"=>49,"name"=>"Fiji","code"=>"FJ"],
        ["id"=>50,"name"=>"Finland","code"=>"FI"],
        ["id"=>51,"name"=>"France","code"=>"FR"],
        ["id"=>52,"name"=>"Gabon","code"=>"GA"],
        ["id"=>53,"name"=>"Georgia","code"=>"GE"],
        ["id"=>54,"name"=>"Germany","code"=>"DE"],
        ["id"=>55,"name"=>"Greece","code"=>"GR"],
        ["id"=>56,"name"=>"Guatemala","code"=>"GT"],
        ["id"=>57,"name"=>"Guinea","code"=>"GN"],
        ["id"=>58,"name"=>"Guyana","code"=>"GY"],
        ["id"=>59,"name"=>"Haiti","code"=>"HT"],
        ["id"=>60,"name"=>"HongKong China","code"=>"HK"],
        ["id"=>61,"name"=>"Horvatia","code"=>"HR"],
        ["id"=>62,"name"=>"Hungary","code"=>"HU"],
        ["id"=>63,"name"=>"Iceland","code"=>"IS"],
        ["id"=>64,"name"=>"India","code"=>"IN"],
        ["id"=>65,"name"=>"Indonesia","code"=>"ID"],
        ["id"=>66,"name"=>"Iran","code"=>"IR"],
        ["id"=>67,"name"=>"Iraq","code"=>"IQ"],
        ["id"=>68,"name"=>"Ireland","code"=>"IE"],
        ["id"=>69,"name"=>"Israel","code"=>"IL"],
        ["id"=>70,"name"=>"Italy","code"=>"IT"],
        ["id"=>71,"name"=>"Ivory Coast","code"=>"CI"],
        ["id"=>72,"name"=>"Jamaica","code"=>"JM"],
        ["id"=>73,"name"=>"Japan","code"=>"JP"],
        ["id"=>74,"name"=>"Jordan","code"=>"JO"],
        ["id"=>75,"name"=>"Kazakhstan","code"=>"KZ"],
        ["id"=>76,"name"=>"Kenya","code"=>"KE"],
        ["id"=>77,"name"=>"Korea (North)","code"=>"KP"],
        ["id"=>78,"name"=>"Korea (South)","code"=>"KR"],
        ["id"=>79,"name"=>"Kyrgyz Rep.","code"=>"KG"],
        ["id"=>80,"name"=>"Latvia","code"=>"LV"],
        ["id"=>81,"name"=>"Lebanon","code"=>"LB"],
        ["id"=>82,"name"=>"Libya","code"=>"LY"],
        ["id"=>83,"name"=>"Lithuania","code"=>"LT"],
        ["id"=>84,"name"=>"Luxembourg","code"=>"LU"],
        ["id"=>85,"name"=>"Madagascar","code"=>"MG"],
        ["id"=>86,"name"=>"Malaysia","code"=>"MY"],
        ["id"=>87,"name"=>"Mauretania","code"=>"MR"],
        ["id"=>88,"name"=>"Mexico","code"=>"MX"],
        ["id"=>89,"name"=>"Moldova","code"=>"MD"],
        ["id"=>90,"name"=>"Monaco","code"=>"MC"],
        ["id"=>91,"name"=>"Mongolia","code"=>"MN"],
        ["id"=>92,"name"=>"Morocco","code"=>"MA"],
        ["id"=>93,"name"=>"Mozambique","code"=>"MZ"],
        ["id"=>94,"name"=>"Namibia","code"=>"NA"],
        ["id"=>95,"name"=>"Nauru","code"=>"NR"],
        ["id"=>96,"name"=>"Nepal","code"=>"NP"],
        ["id"=>97,"name"=>"Netherlands","code"=>"NL"],
        ["id"=>98,"name"=>"New Zealand","code"=>"NZ"],
        ["id"=>99,"name"=>"Norway","code"=>"NO"],
        ["id"=>100,"name"=>"Oman","code"=>"OM"],
        ["id"=>101,"name"=>"Pakistan","code"=>"PK"],
        ["id"=>102,"name"=>"Panama","code"=>"PA"],
        ["id"=>103,"name"=>"Paraguay","code"=>"PY"],
        ["id"=>104,"name"=>"Peru","code"=>"PE"],
        ["id"=>105,"name"=>"Philippines","code"=>"PH"],
        ["id"=>106,"name"=>"Poland","code"=>"PL"],
        ["id"=>107,"name"=>"Portugal","code"=>"PT"],
        ["id"=>108,"name"=>"Qatar","code"=>"QA"],
        ["id"=>109,"name"=>"Romania","code"=>"RO"],
        ["id"=>110,"name"=>"Russia","code"=>"RU"],
        ["id"=>111,"name"=>"Saudi Arabia","code"=>"SA"],
        ["id"=>112,"name"=>"SerbiaMontenegro","code"=>"RS"],
        ["id"=>113,"name"=>"Sierra Leone","code"=>"SL"],
        ["id"=>114,"name"=>"Singapore","code"=>"SG"],
        ["id"=>115,"name"=>"Slovakia","code"=>"SK"],
        ["id"=>116,"name"=>"Slovenia","code"=>"SI"],
        ["id"=>117,"name"=>"Somalia","code"=>"SO"],
        ["id"=>118,"name"=>"South Africa","code"=>"ZA"],
        ["id"=>119,"name"=>"Spain","code"=>"ES"],
        ["id"=>120,"name"=>"Sudan","code"=>"SD"],
        ["id"=>121,"name"=>"Sweden","code"=>"SE"],
        ["id"=>122,"name"=>"Switzerland","code"=>"CH"],
        ["id"=>123,"name"=>"Tanzania","code"=>"TZ"],
        ["id"=>124,"name"=>"Taiwan","code"=>"TW"],
        ["id"=>125,"name"=>"Thailand","code"=>"TH"],
        ["id"=>126,"name"=>"Togo","code"=>"TG"],
        ["id"=>127,"name"=>"Tonga","code"=>"TO"],
        ["id"=>128,"name"=>"Trinidad","code"=>"TT"],
        ["id"=>129,"name"=>"Tunisia","code"=>"TN"],
        ["id"=>130,"name"=>"Turkey","code"=>"TR"],
        ["id"=>131,"name"=>"Tuvalu","code"=>"TV"],
        ["id"=>132,"name"=>"UK","code"=>"UK"],
        ["id"=>133,"name"=>"USA","code"=>"US"],
        ["id"=>134,"name"=>"Uganda","code"=>"UG"],
        ["id"=>135,"name"=>"Ukraine","code"=>"UA"],
        ["id"=>136,"name"=>"Uruguay","code"=>"UY"],
        ["id"=>137,"name"=>"Uzbekistan","code"=>"UZ"],
        ["id"=>138,"name"=>"Venezuela","code"=>"VE"],
        ["id"=>139,"name"=>"Vietnam","code"=>"VN"],
        ["id"=>140,"name"=>"Yemen","code"=>"YE"],
        ["id"=>141,"name"=>"Yugoslavia","code"=>"YU"],
        ["id"=>142,"name"=>"Zimbabwe","code"=>"ZW"],
        ["id"=>143,"name"=>"NO","code"=>null]];

        \App\Country::insert($countries);
    }
}
