<?php

use Illuminate\Database\Seeder;

class CountriesSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = [
            [ 'name' => 'Select one', 'id'=>0],
            [ 'name' => 'Afghanistan',],
            [ 'name' => 'African Rep.',],
            [ 'name' => 'Albania',],
            [ 'name' => 'Algeria',],
            [ 'name' => 'Andorra',],
            [ 'name' => 'Angola',],
            [ 'name' => 'Argentina',],
            [ 'name' => 'Armenia',],
            [ 'name' => 'Australia',],
            [ 'name' => 'Austria',],
            [ 'name' => 'Azerbaijan',],
            [ 'name' => 'Bahamas',],
            [ 'name' => 'Bahrain',],
            [ 'name' => 'Bangladesh',],
            [ 'name' => 'Barbados',],
            [ 'name' => 'Belarus',],
            [ 'name' => 'Belgium',],
            [ 'name' => 'Belize',],
            [ 'name' => 'Benin',],
            [ 'name' => 'Bhutan',],
            [ 'name' => 'Bolivia',],
            [ 'name' => 'Bosnia',],
            [ 'name' => 'Botswana',],
            [ 'name' => 'Brasil',],
            [ 'name' => 'Brunei',],
            [ 'name' => 'Bulgaria',],
            [ 'name' => 'Burkina Faso',],
            [ 'name' => 'Burundi',],
            [ 'name' => 'Cambodia',],
            [ 'name' => 'Cameroon',],
            [ 'name' => 'Canada',],
            [ 'name' => 'Cape_Verde',],
            [ 'name' => 'Chile',],
            [ 'name' => 'China',],
            [ 'name' => 'Chinese Taipei',],
            [ 'name' => 'Colombia',],
            [ 'name' => 'Congo',],
            [ 'name' => 'Croatia',],
            [ 'name' => 'Cuba',],
            [ 'name' => 'Cyprus',],
            [ 'name' => 'Czech Rep. ',],
            [ 'name' => 'Denmark',],
            [ 'name' => 'Ecuador',],
            [ 'name' => 'Egypt',],
            [ 'name' => 'Eritrea',],
            [ 'name' => 'Estonia',],
            [ 'name' => 'Ethiopia',],
            [ 'name' => 'Europe',],
            [ 'name' => 'Fiji',],
            [ 'name' => 'Finland',],
            [ 'name' => 'France',],
            [ 'name' => 'Gabon',],
            [ 'name' => 'Georgia',],
            [ 'name' => 'Germany',],
            [ 'name' => 'Greece',],
            [ 'name' => 'Guatemala',],
            [ 'name' => 'Guinea',],
            [ 'name' => 'Guyana',],
            [ 'name' => 'Haiti',],
            [ 'name' => 'HongKong China',],
            [ 'name' => 'Horvatia',],
            [ 'name' => 'Hungary',],
            [ 'name' => 'Iceland',],
            [ 'name' => 'India',],
            [ 'name' => 'Indonesia',],
            [ 'name' => 'Iran',],
            [ 'name' => 'Iraq',],
            [ 'name' => 'Ireland',],
            [ 'name' => 'Israel',],
            [ 'name' => 'Italy',],
            [ 'name' => 'Ivory Coast',],
            [ 'name' => 'Jamaica',],
            [ 'name' => 'Japan',],
            [ 'name' => 'Jordan',],
            [ 'name' => 'Kazakhstan',],
            [ 'name' => 'Kenya',],
            [ 'name' => 'Korea (North)',],
            [ 'name' => 'Korea (South)',],
            [ 'name' => 'Kyrgyz Rep.',],
            [ 'name' => 'Latvia',],
            [ 'name' => 'Lebanon',],
            [ 'name' => 'Libya',],
            [ 'name' => 'Lithuania',],
            [ 'name' => 'Luxembourg',],
            [ 'name' => 'Madagascar',],
            [ 'name' => 'Malaysia',],
            [ 'name' => 'Mauretania',],
            [ 'name' => 'Mexico',],
            [ 'name' => 'Moldova',],
            [ 'name' => 'Monaco',],
            [ 'name' => 'Mongolia',],
            [ 'name' => 'Morocco',],
            [ 'name' => 'Mozambique',],
            [ 'name' => 'Namibia',],
            [ 'name' => 'Nauru',],
            [ 'name' => 'Nepal',],
            [ 'name' => 'Netherlands',],
            [ 'name' => 'New Zealand',],
            [ 'name' => 'Norway',],
            [ 'name' => 'Oman',],
            [ 'name' => 'Pakistan',],
            [ 'name' => 'Panama',],
            [ 'name' => 'Paraguay',],
            [ 'name' => 'Peru',],
            [ 'name' => 'Philippines',],
            [ 'name' => 'Poland',],
            [ 'name' => 'Portugal',],
            [ 'name' => 'Qatar',],
            [ 'name' => 'Romania',],
            [ 'name' => 'Russia',],
            [ 'name' => 'Saudi Arabia',],
            [ 'name' => 'SerbiaMontenegro',],
            [ 'name' => 'Sierra Leone',],
            [ 'name' => 'Singapore',],
            [ 'name' => 'Slovakia',],
            [ 'name' => 'Slovenia',],
            [ 'name' => 'Somalia',],
            [ 'name' => 'South Africa',],
            [ 'name' => 'Spain',],
            [ 'name' => 'Sudan',],
            [ 'name' => 'Sweden',],
            [ 'name' => 'Switzerland',],
            [ 'name' => 'Tanzania',],
            [ 'name' => 'Taiwan',],
            [ 'name' => 'Thailand',],
            [ 'name' => 'Togo',],
            [ 'name' => 'Tonga',],
            [ 'name' => 'Trinidad',],
            [ 'name' => 'Tunisia',],
            [ 'name' => 'Turkey',],
            [ 'name' => 'Tuvalu',],
            [ 'name' => 'UK',],
            [ 'name' => 'USA',],
            [ 'name' => 'Uganda',],
            [ 'name' => 'Ukraine',],
            [ 'name' => 'Uruguay',],
            [ 'name' => 'Uzbekistan',],
            [ 'name' => 'Venezuela',],
            [ 'name' => 'Vietnam',],
            [ 'name' => 'Yemen',],
            [ 'name' => 'Yugoslavia',],
            [ 'name' => 'Zimbabwe',],
            [ 'name' => 'NO',],
        ];

        \App\Country::insert($countries);
    }
}
