<?php

use Illuminate\Database\Seeder;

class ReplayMapsSeeding extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $replay_map = [
            [ 'name' => 'Andromeda',            'url'=> 'maps/sc/Andromeda.jpg'],
            [ 'name' => 'Arcadia II',           'url'=> 'maps/sc/Arcadia II.jpg'],
            [ 'name' => 'Arkanoid',             'url'=> 'maps/sc/Arkanoid.jpg'],
            [ 'name' => 'Athena 2',             'url'=> 'maps/sc/Athena 2.jpg'],
            [ 'name' => 'Avan-garde II',        'url'=> 'maps/sc/Avan-garde II.jpg'],
            [ 'name' => 'Azalea',               'url'=> 'maps/sc/Azalea.jpg'],
            [ 'name' => 'Back And Belly',       'url'=> 'maps/sc/Back And Belly.jpg'],
            [ 'name' => 'Bifrost',              'url'=> 'maps/sc/Bifrost.jpg'],
            [ 'name' => 'Blade Storm',          'url'=> 'maps/sc/Blade Storm.jpg'],
            [ 'name' => 'Blue Storm',           'url'=> 'maps/sc/Blue Storm.jpg'],
            [ 'name' => 'Byzantium 2',          'url'=> 'maps/sc/Byzantium 2.jpg'],
            [ 'name' => 'Charity',              'url'=> 'maps/sc/Charity.jpg'],
            [ 'name' => 'Colosseum',            'url'=> 'maps/sc/Colosseum.jpg'],
            [ 'name' => 'Colosseum II',         'url'=> 'maps/sc/Colosseum II.jpg'],
            [ 'name' => 'Coulee',               'url'=> 'maps/sc/Coulee.jpg'],
            [ 'name' => 'Crystal Fire',         'url'=> 'maps/sc/Crystal Fire.jpg'],
            [ 'name' => 'Dahlia of Jungle',     'url'=> 'maps/sc/Dahlia of Jungle.jpg'],
            [ 'name' => 'Dark Sauron',          'url'=> 'maps/sc/Dark Sauron.jpg'],
            [ 'name' => 'Destination',          'url'=> 'maps/sc/Destination.jpg'],
            [ 'name' => 'Detonation',           'url'=> 'maps/sc/Detonation.jpg'],
            [ 'name' => 'Dire Straits',         'url'=> 'maps/sc/Dire Straits.jpg'],
            [ 'name' => 'Dream of Balhae',      'url'=> 'maps/sc/Dream of Balhae.jpg'],
            [ 'name' => 'Emperor of Emperor',   'url'=> 'maps/sc/Emperor of Emperor.jpg'],
            [ 'name' => 'Enter The Dragon',     'url'=> 'maps/sc/Enter The Dragon.jpg'],
            [ 'name' => 'Estrella',             'url'=> 'maps/sc/Estrella.jpg'],
            [ 'name' => 'Ever Forte',           'url'=> 'maps/sc/Ever Forte.jpg'],
            [ 'name' => 'Evolution WarpGate',   'url'=> 'maps/sc/Evolution WarpGate.jpg'],
            [ 'name' => 'Eye in the SKY',       'url'=> 'maps/sc/Eye in the SKY.jpg'],
            [ 'name' => 'Forbidden City',       'url'=> 'maps/sc/Forbidden City.jpg'],
            [ 'name' => 'Forbidden Zone',       'url'=> 'maps/sc/Forbidden Zone.jpg'],
            [ 'name' => 'Forest of Abyss',      'url'=> 'maps/sc/Forest of Abyss.jpg'],
            [ 'name' => 'Gaema Gowon',          'url'=> 'maps/sc/Gaema Gowon.jpg'],
            [ 'name' => 'Gaia',                 'url'=> 'maps/sc/Gaia.jpg'],
            [ 'name' => 'Gauntlet2003',         'url'=> 'maps/sc/Gauntlet2003.jpg'],
            [ 'name' => 'GauntletTG',           'url'=> 'maps/sc/GauntletTG.jpg'],
            [ 'name' => 'Gorky Island',         'url'=> 'maps/sc/Gorky Island.jpg'],
            [ 'name' => 'Guillotine',           'url'=> 'maps/sc/Guillotine.jpg'],
            [ 'name' => 'Hall of Valhalla',     'url'=> 'maps/sc/Hall of Valhalla.jpg'],
            [ 'name' => 'Hall of Valhalla V2',  'url'=> 'maps/sc/Hall of Valhalla V2.jpg'],
            [ 'name' => 'Hunters',              'url'=> 'maps/sc/Hunters.jpg'],
            [ 'name' => 'Huntress',             'url'=> 'maps/sc/Huntress.jpg'],
            [ 'name' => 'Hwangsanbul',          'url'=> 'maps/sc/Hwangsanbul.jpg'],
            [ 'name' => 'Incubus',              'url'=> 'maps/sc/Incubus.jpg'],
            [ 'name' => 'Incubus 2004',         'url'=> 'maps/sc/Incubus 2004.jpg'],
            [ 'name' => 'Indian Lament',        'url'=> 'maps/sc/Indian Lament.jpg'],
            [ 'name' => 'Into the Darkness',    'url'=> 'maps/sc/Into the Darkness.jpg'],
            [ 'name' => 'Isles of Siren',       'url'=> 'maps/sc/Isles of Siren.jpg'],
            [ 'name' => 'JRs Memory',           'url'=> 'maps/sc/JRs Memory.jpg'],
            [ 'name' => 'Jungle Story',         'url'=> 'maps/sc/Jungle Story.jpg'],
            [ 'name' => 'Jungle Story V2',      'url'=> 'maps/sc/Jungle Story V2.jpg'],
            [ 'name' => 'Katrina',              'url'=> 'maps/sc/Katrina.jpg'],
            [ 'name' => 'Katrina SE',           'url'=> 'maps/sc/Katrina SE.jpg'],
            [ 'name' => 'Korhal of Ceres',      'url'=> 'maps/sc/Korhal of Ceres.jpg'],
            [ 'name' => 'Labyrinth',            'url'=> 'maps/sc/Labyrinth.jpg'],
            [ 'name' => 'Legacy of Char',       'url'=> 'maps/sc/Legacy of Char.jpg'],
            [ 'name' => 'Longinus',             'url'=> 'maps/sc/Longinus.jpg'],
            [ 'name' => 'Lost Temple',          'url'=> 'maps/sc/Lost Temple.jpg'],
            [ 'name' => 'Luna',                 'url'=> 'maps/sc/Luna.jpg'],
            [ 'name' => 'Martian Cross',        'url'=> 'maps/sc/Martian Cross.jpg'],
            [ 'name' => 'Medusa',               'url'=> 'maps/sc/Medusa.jpg'],
            [ 'name' => 'Mercury',              'url'=> 'maps/sc/Mercury.jpg'],
            [ 'name' => 'Namja Iyagi',          'url'=> 'maps/sc/Namja Iyagi.jpg'],
            [ 'name' => 'NoName',               'url'=> 'maps/sc/NoName.jpg'],
            [ 'name' => 'Nostalgia',            'url'=> 'maps/sc/Nostalgia.jpg'],
            [ 'name' => 'Odin',                 'url'=> 'maps/sc/Odin.jpg'],
            [ 'name' => 'Othello',              'url'=> 'maps/sc/Othello.jpg'],
            [ 'name' => 'Paradoxxx1.0',         'url'=> 'maps/sc/Paradoxxx1.0.jpg'],
            [ 'name' => 'Paradoxxx2.0',         'url'=> 'maps/sc/Paradoxxx2.0.jpg'],
            [ 'name' => 'Parallel Lines 3',     'url'=> 'maps/sc/Parallel Lines 3.jpg'],
            [ 'name' => 'Paranoid Android',     'url'=> 'maps/sc/Paranoid Android.jpg'],
            [ 'name' => 'Pelennor',             'url'=> 'maps/sc/Pelennor.jpg'],
            [ 'name' => 'Plasma',               'url'=> 'maps/sc/Plasma.jpg'],
            [ 'name' => 'Pyth0n',               'url'=> 'maps/sc/Pyth0n.jpg'],
            [ 'name' => 'R-Point',              'url'=> 'maps/sc/R-Point.jpg'],
            [ 'name' => 'Raid Assault',         'url'=> 'maps/sc/Raid Assault.jpg'],
            [ 'name' => 'Remote Outpost',       'url'=> 'maps/sc/Remote Outpost.jpg'],
            [ 'name' => 'Requiem',              'url'=> 'maps/sc/Requiem.jpg'],
            [ 'name' => 'Return of the King',   'url'=> 'maps/sc/Return of the King.jpg'],
            [ 'name' => 'Ride of Valkryies',    'url'=> 'maps/sc/Ride of Valkryies.jpg'],
            [ 'name' => 'Rivalry',              'url'=> 'maps/sc/Rivalry.jpg'],
            [ 'name' => 'River of Flames',      'url'=> 'maps/sc/River of Flames.jpg'],
            [ 'name' => 'Shinhan bakdu 2.4',    'url'=> 'maps/sc/Shinhan bakdu 2.4.jpg'],
            [ 'name' => 'Silent Vortex',        'url'=> 'maps/sc/Silent Vortex.jpg'],
            [ 'name' => 'Sin Pioneer Period',   'url'=> 'maps/sc/Sin Pioneer Period.jpg'],
            [ 'name' => 'Snowbound',            'url'=> 'maps/sc/Snowbound.jpg'],
            [ 'name' => 'So1 815',              'url'=> 'maps/sc/So1 815.jpg'],
            [ 'name' => 'Symmetry of Psy',      'url'=> 'maps/sc/Symmetry of Psy.jpg'],
            [ 'name' => 'Tau Cross',            'url'=> 'maps/sc/Tau Cross.jpg'],
            [ 'name' => 'Tucson',               'url'=> 'maps/sc/Tucson.jpg'],
            [ 'name' => 'U-Boat',               'url'=> 'maps/sc/U-Boat.jpg'],
            [ 'name' => 'Universal Tripod',     'url'=> 'maps/sc/Universal Tripod.jpg'],
            [ 'name' => 'Valley of Wind',       'url'=> 'maps/sc/Valley of Wind.jpg'],
            [ 'name' => 'various',              'url'=> 'maps/sc/various.jpg'],
            [ 'name' => 'Vertigo',              'url'=> 'maps/sc/Vertigo.jpg'],
            [ 'name' => 'XenoSky',              'url'=> 'maps/sc/XenoSky.jpg'],
        ];

        \App\ReplayMap::insert($replay_map);
    }
}
